name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v2
    - name: Install libhunspell
      run: |
        apt update -y && \
        apt install -y --no-install-recommends --no-install-suggests libhunspell-dev hunspell-en-us
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
